package com.sehoprojectmanagerapi.repository.activity;

public enum ActivityEntityType {TAG, TASK, COMMENT, ATTACHMENT, PROJECT, PROJECT_MEMBER, MILESTONE, SPRINT, NOTIFICATION, SPACE, SPACE_MEMBER, WORKSPACE, WORKSPACE_MEMBER, USER, /* 이후 해야될 내용들 ===> */ TASK_ASSIGNEE, TASK_ASSIGNEE_USER, TASK_DEPENDENCY, WORKSPACE_INVITE, WEBHOOK, TEAM, TEAM_MEMBER, TEAM_INVITE}
