package com.sehoprojectmanagerapi.repository.activity;

public enum ActivityEntityType {TAG, TASK, TASK_ASSIGNEE, TASK_ASSIGNEE_USER, TASK_DEPENDENCY, COMMENT, ATTACHMENT, PROJECT, PROJECT_MEMBER, MILESTONE, SPRINT, NOTIFICATION, SPACE, SPACE_MEMBER, WORKSPACE, WORKSPACE_MEMBER, WORKSPACE_INVITE, WEBHOOK, TEAM, TEAM_MEMBER, TEAM_INVITE}
